# Generated by Django 3.1.4 on 2021-06-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quiestion',
            new_name='question',
        ),
    ]
